name: My GitHub Actions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs :
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0 # Use the desired Terraform version

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan
      

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      